FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY drasi_consumer.py .

CMD ["python", "-u", "drasi_consumer.py"]
